[template]
cargo_generate_version = ">= 0.17.0, < 0.20.0"

[placeholders]
description = { type="string", prompt="Description for the project?" }
tokenMetadataBaseURL= { type="string", prompt="Token metadata base URL of the token?", default='https://some.example/token/' }
