# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "ci_pipeline"
version = "0.1.0"
edition = "2018"
license = "MPL-2.0"
description = "This toml file is for the CI pipeline"
authors = [ "Concordium <developers@concordium.com>" ]

[features]
default = ["std"]
std = ["concordium-std/std", "concordium-cis2/std"]

[dependencies]
concordium-std = "4.0.0"
concordium-cis2 = "1.2.0"

[lib]
crate-type=["cdylib", "rlib"]

[profile.release]
opt-level = "s"
codegen-units = 1
