combine_control_expr = false
wrap_comments = true
brace_style = "PreferSameLine"
enum_discrim_align_threshold = 20
fn_single_line = true
format_strings = true
format_macro_matchers = true
format_macro_bodies = true
merge_imports = true
normalize_comments = false
reorder_impl_items = true
reorder_imports = true
struct_field_align_threshold = 20
trailing_semicolon = true
type_punctuation_density = "Wide"
use_field_init_shorthand = true
use_try_shorthand = true
format_code_in_doc_comments = true
overflow_delimited_expr = true
normalize_doc_attributes = true
use_small_heuristics = "Off"
