[package]
name = "two-step-transfer"
version = "0.1.1"
authors = ["Concordium <developers@concordium.com>"]
edition = "2018"
license = "MPL-2.0"
description = "Two-step transfer smart contract."
homepage = "https://github.com/concordium/concordium-rust-smart-contracts"
repository = "https://github.com/concordium/concordium-rust-smart-contracts"
readme = "../README.md"

[features]
default = ["std"]

std = ["concordium-std/std", "concordium-std/concordium-quickcheck"]

[dependencies.concordium-std]
# git = "https://github.com/Concordium/concordium-std.git"
# branch = "main"
version = "3.0"
path = "../../concordium-std"
default-features = false

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = 3
