[package]
name = "two-step-transfer"
version = "0.1.1"
authors = ["Concordium <developers@concordium.com>"]
edition = "2018"
license = "MPL-2.0"
description = "Two-step transfer smart contract."
homepage = "https://github.com/concordium/concordium-rust-smart-contracts"
repository = "https://github.com/concordium/concordium-rust-smart-contracts"
readme = "../README.md"

[features]
default = ["std"]

std = ["concordium-std/std"]

[dependencies.concordium-std]
version = "5"
path = "../../concordium-std"
features = []
default-features = false

[dev-dependencies.concordium-std]
features = ["concordium-quickcheck"]

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = 3
