[package]
name = "two-step-transfer"
version = "0.1.1"
authors = ["Concordium <developers@concordium.com>"]
edition = "2021"
license = "MPL-2.0"
description = "Two-step transfer smart contract."
homepage = "https://github.com/concordium/concordium-rust-smart-contracts"
repository = "https://github.com/concordium/concordium-rust-smart-contracts"
readme = "../README.md"

[features]
default = ["std", "bump_alloc"]

std = ["concordium-std/std"]
bump_alloc = ["concordium-std/bump_alloc"]

[dependencies.concordium-std]
version = "*"
path = "../../concordium-std"
default-features = false
features = ["concordium-quickcheck", "wasm-test"]

[dev-dependencies]
concordium-std = { version = "*", path = "../../concordium-std" }
concordium-std-derive = { path = "../../concordium-std-derive" }

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = 3
