[package]
name = "piggy-bank-part2"
version = "0.1.1"
authors = ["Concordium <developers@concordium.com>"]
edition = "2021"
license = "MPL-2.0"
description = "Piggy bank smart contract part 2."
homepage = "https://github.com/concordium/concordium-rust-smart-contracts"
repository = "https://github.com/concordium/concordium-rust-smart-contracts"
readme = "../README.md"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["std", "bump_alloc"]
std = ["concordium-std/std"]
bump_alloc = ["concordium-std/bump_alloc"]

[dependencies.concordium-std]
version = "9"
path = "../../../concordium-std"
default-features = false

[dev-dependencies]
concordium-smart-contract-testing = { path = "../../../contract-testing" }

[profile.release]
opt-level = 3
