[package]
name = "concordium-std-derive"
version = "4.2.0"
authors = ["Concordium <developers@concordium.com>"]
edition = "2018"
license = "MPL-2.0"
description = "Procedural macros to ease writing smart contracts on the Concordium blockchain."
homepage = "https://github.com/Concordium/concordium-rust-smart-contracts/"
repository = "https://github.com/Concordium/concordium-rust-smart-contracts/"
readme = "./README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
syn = { version = "1.0.63", features = [ "full", "extra-traits" ] }
quote = "1.0"
proc-macro2 = "1.0"

[dependencies.concordium-contracts-common]
path = "../concordium-contracts-common/concordium-contracts-common"
version = "4.1"
default-features = false

[lib]
proc-macro = true

[features]
wasm-test = []
build-schema = []
concordium-quickcheck = []